export type RealEstateOffer = {
  currentOfferURL: string;
  offerID: number;
  titleKategoria: string;
  offerTitle: string;
  priceInfo: number;
  areaPriceInfo: string;
  areaInfo: string;
  plotTypeInfo: string | null;
  landAreaInfo: string | null;
  plotLengthInfo: string | null;
  plotWidthInfo: string | null;
  numberOfOfferInfo: string;
  publishedInfo: string;
  descriptionInfo: string;
  "googleMapsInfo/0": number;
  "googleMapsInfo/1": number;
  telephoneNumberInfo: string;
  sellerInfo: string;
  estateAgencyInfo: string;
  cityInfo: string;
  numberOfRoomsInfo: string;
  usableArea: string;
  floorInfo: string;
  numbersOfFloorsInfo: string;
  numberOfBathroomsInfo: string | null;
  typeOfKitchenInfo: string;
  isBathroomSeparateInfo: string | null;
  windowWoodworkInfo: string | null;
  marketInfo: string;
  formOfPropertyInfo: string;
  typeOfBuildingInfo: string | null;
  yearOfConstructionInfo: string;
  conditionOfThePropertyInfo: string;
  heatingInfo: string;
  balconyInfo: string;
  balconyAreaInfo: string | null;
  buildingMaterialInfo: string | null;
  conditionOfTheBuildingInfo: string | null;
  typeOfHouseInfo: string | null;
  interiorHeightInfo: string | null;
  numbersOfLevelsInfo: string | null;
  numbersOfBedroomsInfo: string | null;
  bathroomAreaInfo: string | null;
  terraceInfo: string | null;
  terraceAreaInfo: string | null;
  gardenAreaInfo: string | null;
};
