import type { Metadata } from "next";
import React from "react";
import { fetchData } from "../_utils/fetchData";
import { supabase } from "../_utils/superbaseClient";
import { Suspense } from "react";
import styles from "../_styles/Offers.module.css";
import ListingItem from "../_components/ListItem/ListingItem";
import Link from "next/link";
import { type } from "os";
import Pagination from "../_components/Pagination/Pagination";
export const metadata: Metadata = {
  title: "Offers of AnyTown Real Estate",
  description: "Generated by create next app",
};

async function Offers({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  const albafefe = searchParams.page;
  const page = searchParams["page"] ?? "1";
  const limit = searchParams["limit"] ?? "5";
  const start = (Number(page) - 1) * Number(limit);
  const end = start + Number(limit); //number
  console.log(
    albafefe,
    "searchParams:",
    searchParams,
    "page:",
    page,
    "limit:",
    limit,
    "start:",
    start,
    "end:",
    end
  );
  //zrobić typy dla ofert
  /*    const offersData = fetchData()
  const offersFetched = await offersData; */
  let { data: Offers, error } = await supabase
    .from("Offers")
    .select("*")
    .range(start, end - 1);

  /*  const items = Array.from({ length: 10 }, (_, index) => (
    <ListingItem key={index} />
  )); */

  console.log("offers.length:", Offers?.length);

  const Data = () => {
    return Offers?.map((item) => (
      <Link href={`/offers/${item.offerID.toString()}`}>
        <ListingItem key={item.offerID} data={item} />
      </Link>
    ));
  };
  return (
    <section className={styles.section_container}>
      Offers
      <Data />
      <Pagination />
      {/* props totalpages number */}
    </section>
  );
}

export default Offers;
